name: chats
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  google_fonts: ^4.0.3
  provider: ^6.0.5
  flutter_screenutil: ^5.6.0
  smooth_page_indicator: ^1.0.0+2
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  loading_animation_widget: ^1.2.0+4
  shared_preferences: ^2.0.17
  country_picker: ^2.0.19
  image_picker: ^0.8.6+1
  uuid: ^3.0.7
  intl: ^0.17.0
  video_player: ^2.5.1
  flutter_contacts: ^1.1.6
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0
  path_provider: ^2.0.12
  audioplayers: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/